apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    createdAt: "2025-03-15T06:59:20Z"
    operators.operatorframework.io/builder: operator-sdk-v1.39.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: app-manager-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - name: appinstances.apps.sanjitmohanty.in
        kind: AppInstance
        version: v1alpha1
        displayName: "App Instance"
        description: "Defines an AppInstance resource"
  description: application manager operator
  displayName: app-manager-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - app-manager
  links:
  - name: App Manager Operator
    url: https://app-manager-operator.domain
  maturity: alpha
  provider:
    name: sanjitmohanty
  version: 0.0.0
