# permissions for end users to view appinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: app-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: appinstance-viewer-role
rules:
- apiGroups:
  - apps.sanjitmohanty.in
  resources:
  - appinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.sanjitmohanty.in
  resources:
  - appinstances/status
  verbs:
  - get
