apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: app-manager-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AppInstance is the Schema for the appinstances API
      displayName: App Instance
      kind: AppInstance
      name: appinstances.apps.sanjitmohanty.in
      version: v1alpha1
  description: application manager operator
  displayName: app-manager-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - app-manager
  links:
  - name: App Manager Operator
    url: https://app-manager-operator.domain
  maturity: alpha
  provider:
    name: sanjitmohanty
  version: 0.0.0
